#include <iostream>
using namespace std;

int main()
{
    char op; // variable to store the operator
    float num1, num2; // variables to store the operands
    cout << "Enter operator: +, -, *, /: "; // prompt the user for operator
    cin >> op; // read the operator from the user
    cout << "Enter two operands: "; // prompt the user for operands
    cin >> num1 >> num2; // read the operands from the user

    switch(op) // switch statement to check the operator
    {
        case '+': // if the operator is +
            cout << num1 << " + " << num2 << " = " << num1 + num2; // print the result of addition
            break; // break out of switch statement
        case '-': // if the operator is -
            cout << num1 << " - " << num2 << " = " << num1 - num2; // print the result of subtraction
            break; // break out of switch statement
        case '*': // if the operator is *
            cout << num1 << " * " << num2 << " = " << num1 * num2; // print the result of multiplication
            break; // break out of switch statement
        case '/': // if the operator is /
            cout << num1 << " / " << num2 << " = " << (num1 / num2); // print the result of division (cast to float)
            break; // break out of switch statement
        default: // if none of the above cases match
            cout << "Error! Operator is not correct"; // print an error message
            break; // break out of switch statement
    }

    return 0;
}

//Generated by Bing AI